In [1]:
import numpy as np
import scipy.sparse as sm
import numpy.linalg as la
import scipy.sparse.linalg as sml
import matplotlib.pyplot as plt
from IPython.display import HTML
from matplotlib.animation import FuncAnimation

In [70]:
def Mat_AB(x,y,r):
    Nx , Ny = len(x)-2 , len(y)-2
    N = Nx*Ny
    A , B = np.zeros((N,N)) , np.zeros((N,N))
    d_A , d_B , mr= 1+4*r , 1-4*r , -r
    for i in range(Nx):
        for j in range(Ny):
            A[i*Ny + j ,i*Ny + j] , B[i*Ny + j,i*Ny + j] =  1,1 #d_A , d_B
    for i in range(Nx-1):
        for j in range(Ny):
            A[(i+1)*Ny + j ,i*Ny + j] , B[(i+1)*Ny + j ,i*Ny + j] = 2,2 #mr , mr
            A[i*Ny + j ,(i+1)*Ny + j] , B[(i+1)*Ny + j ,i*Ny + j] = 2,2 #mr , mr
    for i in range(Nx):
        for j in range(Ny-1):
            A[i*Ny + j ,i*Ny + j+1] , B[i*Ny + j,i*Ny + j+1] =  3,3 #mr , mr
            A[i*Ny + j+1 ,i*Ny + j] , B[i*Ny + j+1,i*Ny + j] =  3,3 #mr , mr
    return A , B

In [71]:
x , y = np.linspace(0,1,6) , np.linspace(0,1,5)
A,B = Mat_AB(x,y,0.5)
A

array([[1., 3., 0., 2., 0., 0., 0., 0., 0., 0., 0., 0.],
       [3., 1., 3., 0., 2., 0., 0., 0., 0., 0., 0., 0.],
       [0., 3., 1., 0., 0., 2., 0., 0., 0., 0., 0., 0.],
       [2., 0., 0., 1., 3., 0., 2., 0., 0., 0., 0., 0.],
       [0., 2., 0., 3., 1., 3., 0., 2., 0., 0., 0., 0.],
       [0., 0., 2., 0., 3., 1., 0., 0., 2., 0., 0., 0.],
       [0., 0., 0., 2., 0., 0., 1., 3., 0., 2., 0., 0.],
       [0., 0., 0., 0., 2., 0., 3., 1., 3., 0., 2., 0.],
       [0., 0., 0., 0., 0., 2., 0., 3., 1., 0., 0., 2.],
       [0., 0., 0., 0., 0., 0., 2., 0., 0., 1., 3., 0.],
       [0., 0., 0., 0., 0., 0., 0., 2., 0., 3., 1., 3.],
       [0., 0., 0., 0., 0., 0., 0., 0., 2., 0., 3., 1.]])

In [26]:
A = np.arange(1,7)
A 

array([1, 2, 3, 4, 5, 6])

In [38]:
B = A.reshape(2,3)
B

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
B.transpose().reshape(1,6)[0]

array([1, 4, 2, 5, 3, 6])