In [1]:
import numpy as np
import numpy.linalg as la
import scipy.sparse as sm
import scipy.sparse.linalg as sml

In [2]:
A = np.array([ [0,3,0],[7,0,0],[0,0,1] ])
print(np.dot(A,A))
A

[[21  0  0]
 [ 0 21  0]
 [ 0  0  1]]


array([[0, 3, 0],
       [7, 0, 0],
       [0, 0, 1]])

In [3]:
B = sm.csc_matrix([ [0,3,0],[7,0,0],[0,0,1] ])
print(B)
B.toarray()

  (1, 0)	7
  (0, 1)	3
  (2, 2)	1


array([[0, 3, 0],
       [7, 0, 0],
       [0, 0, 1]])

In [4]:
B = sm.csr_matrix([ [0,3,0],[7,0,0],[0,0,1] ])
print(B)
B.toarray()

  (0, 1)	3
  (1, 0)	7
  (2, 2)	1


array([[0, 3, 0],
       [7, 0, 0],
       [0, 0, 1]])

In [5]:
print(np.dot(B,B))

  (0, 0)	21
  (1, 1)	21
  (2, 2)	1


In [6]:
B.toarray()

array([[0, 3, 0],
       [7, 0, 0],
       [0, 0, 1]])

In [7]:
B = sm.csc_matrix([ [0,3,0],[7,0,0],[0,0,1] ])
B_inv = sml.inv(B)

In [8]:
%%timeit
B2_dot = np.dot(B,B)
B2_dot

42.7 µs ± 117 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [9]:
%%timeit
B2_arr = B@B
B2_arr

35.8 µs ± 163 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [10]:
B@B_inv.toarray()

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
v = np.array([1,2,3]) 

In [12]:
np.dot(B,v)

array([<3x3 sparse matrix of type '<class 'numpy.int64'>'
       	with 3 stored elements in Compressed Sparse Column format>,
       <3x3 sparse matrix of type '<class 'numpy.int64'>'
       	with 3 stored elements in Compressed Sparse Column format>,
       <3x3 sparse matrix of type '<class 'numpy.int64'>'
       	with 3 stored elements in Compressed Sparse Column format>],
      dtype=object)

In [13]:
B@v

array([6, 7, 3])

In [14]:
A = np.arange(1,7)
A 

array([1, 2, 3, 4, 5, 6])

In [15]:
B = A.reshape(2,3)
B

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
B_vec = B.transpose().reshape(1,6)[0]
B_vec

array([1, 4, 2, 5, 3, 6])

In [17]:
B_vec.reshape(3,2).transpose()

array([[1, 2, 3],
       [4, 5, 6]])