In [20]:
import numpy as np
import numpy.linalg as la
import scipy.sparse as sm
import scipy.sparse.linalg as sml

In [9]:
A = np.array([ [0,3,0],[7,0,0],[0,0,1] ])
print(np.dot(A,A))
A

[[21  0  0]
 [ 0 21  0]
 [ 0  0  1]]


array([[0, 3, 0],
       [7, 0, 0],
       [0, 0, 1]])

In [14]:
B = sm.csc_matrix([ [0,3,0],[7,0,0],[0,0,1] ])
print(B)
B.toarray()

  (1, 0)	7
  (0, 1)	3
  (2, 2)	1


array([[0, 3, 0],
       [7, 0, 0],
       [0, 0, 1]])

In [15]:
B = sm.csr_matrix([ [0,3,0],[7,0,0],[0,0,1] ])
print(B)
B.toarray()

  (0, 1)	3
  (1, 0)	7
  (2, 2)	1


array([[0, 3, 0],
       [7, 0, 0],
       [0, 0, 1]])

In [12]:
print(np.dot(B,B))

  (0, 0)	21
  (1, 1)	21
  (2, 2)	1


In [13]:
B.toarray()

array([[0, 3, 0],
       [7, 0, 0],
       [0, 0, 1]])

In [27]:
B = sm.csc_matrix([ [0,3,0],[7,0,0],[0,0,1] ])
B_inv = sml.inv(B)

In [29]:
np.dot(B,B_inv).toarray()

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
B@B.toarray()

array([[21,  0,  0],
       [ 0, 21,  0],
       [ 0,  0,  1]])

In [32]:
B@B_inv.toarray()

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])