In [20]:
import numpy as np
import numpy.linalg as la
import scipy.sparse as sm
import scipy.sparse.linalg as sml

In [9]:
A = np.array([ [0,3,0],[7,0,0],[0,0,1] ])
print(np.dot(A,A))
A

[[21  0  0]
 [ 0 21  0]
 [ 0  0  1]]


array([[0, 3, 0],
       [7, 0, 0],
       [0, 0, 1]])

In [14]:
B = sm.csc_matrix([ [0,3,0],[7,0,0],[0,0,1] ])
print(B)
B.toarray()

  (1, 0)	7
  (0, 1)	3
  (2, 2)	1


array([[0, 3, 0],
       [7, 0, 0],
       [0, 0, 1]])

In [15]:
B = sm.csr_matrix([ [0,3,0],[7,0,0],[0,0,1] ])
print(B)
B.toarray()

  (0, 1)	3
  (1, 0)	7
  (2, 2)	1


array([[0, 3, 0],
       [7, 0, 0],
       [0, 0, 1]])

In [12]:
print(np.dot(B,B))

  (0, 0)	21
  (1, 1)	21
  (2, 2)	1


In [13]:
B.toarray()

array([[0, 3, 0],
       [7, 0, 0],
       [0, 0, 1]])

In [34]:
B = sm.csc_matrix([ [0,3,0],[7,0,0],[0,0,1] ])
B_inv = sml.inv(B)

In [45]:
%%timeit
B2_dot = np.dot(B,B)
B2_dot

43.6 µs ± 243 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [46]:
%%timeit
B2_arr = B@B
B2_arr

35.9 µs ± 91.6 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [32]:
B@B_inv.toarray()

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [49]:
v = np.array([1,2,3]) 

In [51]:
np.dot(B,v)

array([<3x3 sparse matrix of type '<class 'numpy.int64'>'
       	with 3 stored elements in Compressed Sparse Column format>,
       <3x3 sparse matrix of type '<class 'numpy.int64'>'
       	with 3 stored elements in Compressed Sparse Column format>,
       <3x3 sparse matrix of type '<class 'numpy.int64'>'
       	with 3 stored elements in Compressed Sparse Column format>],
      dtype=object)

In [56]:
B@v

array([6, 7, 3])